-- MySQL Script generated by MySQL Workbench
-- Wed Aug 23 23:21:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lpv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lpv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lpv` DEFAULT CHARACTER SET utf8 ;
USE `lpv` ;

-- -----------------------------------------------------
-- Table `lpv`.`Cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpv`.`Cidades` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idCidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpv`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpv`.`Alunos` (
  `Matricula` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(2) NOT NULL,
  `EstadoCivil` INT NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`Matricula`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  INDEX `fk_Alunos_Cidades` (`idCidade` ASC),
  CONSTRAINT `fk_Alunos_Cidades`
    FOREIGN KEY (`idCidade`)
    REFERENCES `lpv`.`Cidades` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
