-- Generated by Oracle SQL Developer Data Modeler Version: 2.0.0 Build: 584
--   at:        2017-07-06 20:57:18
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE Bairros 
    ( 
     IDBairro NUMBER (5)  NOT NULL , 
     Nome VARCHAR2 (30) , 
     Cidades_IDCidade NUMBER (5)  NOT NULL 
    ) 
;



ALTER TABLE Bairros 
    ADD CONSTRAINT Bairros_PK PRIMARY KEY ( IDBairro ) ;


CREATE TABLE Cidades 
    ( 
     IDCidade NUMBER (5)  NOT NULL , 
     Nome VARCHAR2 (30) , 
     Estados_IDEstado NUMBER (5)  NOT NULL 
    ) 
;



ALTER TABLE Cidades 
    ADD CONSTRAINT Cidades_PK PRIMARY KEY ( IDCidade ) ;


CREATE TABLE Estados 
    ( 
     IDEstado NUMBER (5)  NOT NULL , 
     Nome VARCHAR2 (30) , 
     Paises_IDPais NUMBER (5)  NOT NULL 
    ) 
;



ALTER TABLE Estados 
    ADD CONSTRAINT Estados_PK PRIMARY KEY ( IDEstado ) ;


CREATE TABLE Paises 
    ( 
     IDPais NUMBER (5)  NOT NULL , 
     Nome VARCHAR2 (31) 
    ) 
;



ALTER TABLE Paises 
    ADD CONSTRAINT Paises_PK PRIMARY KEY ( IDPais ) ;


CREATE TABLE Ruas 
    ( 
     IDRua NUMBER (5)  NOT NULL , 
     Nome VARCHAR2 (30) , 
     Bairros_IDBairro NUMBER (5)  NOT NULL 
    ) 
;



ALTER TABLE Ruas 
    ADD CONSTRAINT Ruas_PK PRIMARY KEY ( IDRua ) ;



ALTER TABLE Bairros 
    ADD CONSTRAINT Bairros_Cidades_FK FOREIGN KEY 
    ( 
     Cidades_IDCidade
    ) 
    REFERENCES Cidades 
    ( 
     IDCidade
    ) 
;


ALTER TABLE Cidades 
    ADD CONSTRAINT Cidades_Estados_FK FOREIGN KEY 
    ( 
     Estados_IDEstado
    ) 
    REFERENCES Estados 
    ( 
     IDEstado
    ) 
;


ALTER TABLE Estados 
    ADD CONSTRAINT Estados_Paises_FK FOREIGN KEY 
    ( 
     Paises_IDPais
    ) 
    REFERENCES Paises 
    ( 
     IDPais
    ) 
;


ALTER TABLE Ruas 
    ADD CONSTRAINT Ruas_Bairros_FK FOREIGN KEY 
    ( 
     Bairros_IDBairro
    ) 
    REFERENCES Bairros 
    ( 
     IDBairro
    ) 
;


    
    
    
    
    

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- CREATE PROCEDURE                         0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE SNAPSHOT                          0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
